export default [
  { value: '1002', label: 'Automotive (Cars, Trucks, Racing)' },
  { value: '1011', label: 'Aut ' },
  { value: '1110', label: 'Automo' },
  { value: '1102', label: 'Au' },
  { value: '1008', label: 'eSports & Video Games' },
  { value: '1012', label: 'Politics' },
  { value: '1022', label: 'Sports' },
  { value: '1024', label: 'Technology' },
  { value: '1025', label: 'Television' },
  { value: '1028', label: 'Comedy' },
  { value: '1029', label: 'Digital Creators' },
  { value: '1030', label: 'Entertainment & Pop Culture' },
  { value: '1031', label: 'Financial & Business News' },
  { value: '1032', label: 'Food & Drink' },
  { value: '1033', label: 'Lifestyle (Fashion, Travel, Wellness)' },
  { value: '1034', label: 'Music' },
  { value: '1035', label: 'News & Current Events' },
  { value: '1036', label: 'Science & Education' },
]
